# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  batch: false
  branches:
    include: 
      - main 

pr: 
  autoCancel: false
  drafts: true
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

variables:
  # Disable Husky in the CI environment
  - name: 'husky'
    value: 0

  # NodeJS Version
  - name: 'nodeVersion'
    value: '18.7.0'

  # NPM Version
  - name: 'npmVersion'
    value: '7'

  # NPM Cache Directory
  - name: 'npm_config_cache'
    value: $(Pipeline.Workspace)/.npm

  # Are we building the main branch
  - name: 'isMain'
    value: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]

  # Azure Artifact Feed, this must align with the values in .npmrc
  - name: artifactFeedId
    value: '3387aaee-45af-46d2-8edc-e275fb504a12'

stages: 
  - stage: Build
    jobs:  
      - job: Build
        displayName: build

        steps:
          - checkout: self
            clean: true
            persistCredentials: true
            displayName: Checkout

          - task: Cache@2
            inputs:
              key: 'npm | "$(Agent.OS)" | package-lock.json'
              path: $(npm_config_cache)
            displayName: Npm Module Cache

          - task: NodeTool@0
            inputs:
              versionSpec: $(nodeVersion)
            displayName: Node Install $(nodeVersion)

          - task: Npm@1
            inputs:
              command: ci
              customRegistry: 'useFeed'
              customFeed: $(artifactFeedId)
            displayName: Install
          
          - task: Npm@1
            inputs:
              command: custom
              customCommand: run test:unit
              customRegistry: 'useFeed'
            displayName: Unit Tests

          - script: |
             npm install
             npm run build:android
            displayName: Build Android
          
          - script: | 
             npm install
             npm run build:ios
            displayName: Build IOS


